### ISSUE TITLE
Push

### ISSUE THREAD

**Issue by brunoilponseisae** [AnTerZz/tournois-antoine-rieuneau#1]
Pense à faire des pushs régulier afin que l'on puisse te commenter ton code.

**Comment by AnTerZz** [comment]
Avez vous vu les push dans la branche dev ? J'attendais d'avoir quelquechose de stable pour merge.

**Comment by brunoilponseisae** [comment]
Ha non. Je n'avais pas vérifié. Merci! Je regarde ça.
